"""Record session facts in code instead of asking an agent to maintain state.

A client hook invokes this module when a session ends. Any supported harness can call
the same command, so the mechanism is vendor-neutral. The agent does not know about the
mechanism and never edits the journal itself, which avoids contention over a state file.

The capture contains facts only: branch and HEAD, commits since the previous capture,
and uncommitted files. It appends to ``.agent/journal/YYYY-MM-DD.md`` and does nothing
when the repository has not changed. Semantic decisions such as the next step remain a
human responsibility in ``.agent/state.md``.

This repository owns its copy, derived from a neutral internal template.
"""
from __future__ import annotations

import subprocess
import sys
from datetime import datetime
from pathlib import Path

from .fs import atomic_write


def _git(repo_root: Path, *args: str) -> str:
    proc = subprocess.run(["git", *args], capture_output=True, text=True, cwd=repo_root)
    return proc.stdout.strip() if proc.returncode == 0 else ""


def capture(repo_root: Path) -> Path | None:
    """Append a factual snapshot, or return ``None`` when nothing changed."""
    if not (repo_root / ".git").exists():
        return None

    journal_dir = repo_root / ".agent" / "journal"
    journal_dir.mkdir(parents=True, exist_ok=True)
    marker = journal_dir / ".last-capture"  # runtime marker, outside git (journal/.gitignore)

    branch = _git(repo_root, "rev-parse", "--abbrev-ref", "HEAD") or "-"
    head = _git(repo_root, "rev-parse", "HEAD")
    dirty = _git(repo_root, "status", "--porcelain")
    last_head = marker.read_text().strip() if marker.is_file() else ""

    if head == last_head and not dirty:
        return None  # nothing changed since the previous capture

    if last_head:
        commits = _git(repo_root, "log", "--oneline", f"{last_head}..{head}")
    else:
        commits = _git(repo_root, "log", "--oneline", "-5")

    now = datetime.now()
    lines = [f"## {now:%H:%M} - branch {branch} @ {head[:9] or '-'}"]
    if commits:
        lines.append("commits since the previous capture:")
        lines += [f"- {c}" for c in commits.splitlines()]
    if dirty:
        files = dirty.splitlines()
        lines.append(f"uncommitted: {len(files)} files")
        lines += [f"- {f.strip()}" for f in files[:15]]
        if len(files) > 15:
            lines.append(f"- ... {len(files) - 15} more")
    diffstat = _git(repo_root, "diff", "--shortstat")
    if diffstat:
        lines.append(f"diff: {diffstat}")
    day_file = journal_dir / f"{now:%Y-%m-%d}.md"
    new_day = not day_file.exists()
    if new_day:
        before = f"# Journal {now:%Y-%m-%d} (generated by session-capture, do not edit by hand)"
    else:
        before = day_file.read_text(encoding="utf-8").rstrip()
    # Blocks are separated by a single blank line, but the file ends with exactly one LF:
    # otherwise git diff --check complains about the generated journal after every capture.
    atomic_write(day_file, before + "\n\n" + "\n".join(lines) + "\n")
    marker.write_text(head)
    return day_file


def main() -> int:
    """Capture the repository containing cwd and always exit successfully.

    Hooks run from the project directory. If cwd is not in a Git repository, cwd itself
    is used. A failed capture must never break the client's session shutdown.
    """
    root = _git(Path.cwd(), "rev-parse", "--show-toplevel")
    capture(Path(root) if root else Path.cwd())
    return 0


if __name__ == "__main__":
    sys.exit(main())
